config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "about", to: "home#about"
  get "contact", to: "home#contact"
  get "friends", to: "home#friends"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users
  resources :timelines, only: [:index, :create, :destroy]
  resources :friendships, only: :create
  resources :messages, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :from_user, class_name: "User"
  belongs_to :to_user, class_name: "User"
  validates :from_user_id, presence: true
  validates :to_user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  default_scope -> {order(created_at: :asc)}

  belongs_to :from_user, class_name: "User"
  belongs_to :from_user, class_name: "User"
  validates :content, presence: true, length: { maximum: 50 }
  validates :from_user_id, presence: true
  validates :to_user_id, presence: true
  validates :room_id, presence: true

  def Message.recent_in_room(room_id)
    where(room_id: room_id).last(100)
  end
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  default_scope -> {order(created_at: :desc)}
  belongs_to :user, dependent: :destroy

  validates :content, presence: true, length: { maximum: 255 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :from_user_friendships, class_name: "Friendship", foreign_key: "from_user_id", dependent: :destroy
  has_many :from_user, through: :from_user_friendships, source: :to_user
  has_many :to_user_friendships, class_name: "Friendship", foreign_key: "to_user_id", dependent: :destroy
  has_many :to_user, through: :to_user_friendships, source: :from_user

  has_many :from_user_messages, class_name: "Message", foreign_key: "from_user_id", dependent: :destroy
  has_many :send_user, through: :from_user_messages, source: :to_user
  has_many :to_user_messages, class_name: "Message", foreign_key: "to_user_id", dependent: :destroy
  has_many :recieved_user, through: :to_user_messages, source: :from_user

  has_many :timelines

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true

  has_secure_password

  def friends
    from_user + to_user
  end

  def become_friend(other_user)
    from_user << other_user
  end

  def from_friend?(other_user)
		from_user.include?(other_user)
  end
  
  def to_friend?(user)
    to_user.include?(user)
  end

  def send_message?(other_user)
		send_user.include?(other_user)
  end
  
  def recieved_friend?(user)
    recieved_user.include?(user)
  end

  def send_message(other_user, room_id, content)
    from_user_messages.create!(to_user_id: other_user, room_id: room_id, content: content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインが必要です。"
        redirect_to login_url
      end
    end

    def message_room_id(first_user, second_user)
      first_id = first_user.id.to_i
      second_id = second_user.id.to_i
      if first_id < second_id
        "#{first_user.id}-#{second_user.id}"
      else
        "#{second_user.id}-#{first_user.id}"
      end
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :logged_in_user

  def create
    user = User.find(params[:to_user_id])
    current_user.become_friend(user)
    flash[:success] = "#{user.name}さんと友達になりました。"
    redirect_to users_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "top_application"

  def index
    redirect_to current_user if logged_in?
  end

  def about
  end

  def contact
  end

  def friends
    @friends = current_user.friends
    render layout: "application"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    user = User.find_by(id: params[:to_user_id])
    current_user.send_message(params[:to_user_id], params[:room_id], params[:message][:content])
    flash[:success] = "メッセージを投稿しました。"
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "top_application"
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "ログインしました。"
      redirect_back_or user
    else
      flash[:danger] = "ログインに失敗しました。"
      render "new"
    end
  end

  def destroy
    flash[:success] = "ログアウトしました。"
    log_out
    redirect_to root_path
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :logged_in_user, only: [:index, :create, :destroy]

  def index
    @timelines = Timeline.paginate(page: params[:page], per_page: 10)
  end

  def create
    tl = current_user.timelines.create(params_tls)
    if tl.save
      flash[:success] = "投稿に成功しました。"
      redirect_to timelines_path
    else
      flash[:danger] = "何か入力してください"
      render "index"
    end
  end

  def destroy
    flash[:success] = "投稿を削除しました。"
    Timeline.find_by(id: params[:id]).delete
    redirect_to timelines_path
  end

  private
    def params_tls
      params.require(:tl).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "top_application"

  before_action :logged_in_user, only: [:index, :show]
  before_action :correct_user, only: [:edit, :udpate, :destroy]

  def index
    @users = User.all
    render layout: "application"
  end

  def show
    @user = User.find(params[:id])
    @room_id = message_room_id(current_user, @user)
    @messages = Message.recent_in_room(@room_id)
    render layout: "application"
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "登録に成功しました。"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find_by(id: params[:id])
      unless current_user == @user
        flash[:danger] = "アクセス権限がありません。"
        redirect_to current_user
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if !session[:user_id].nil?
      current_user = User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    current_user == user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_sidebar.html.erb
<div class="flex flex-direction">
  <ul>
    <li><%= link_to "トーク", "#" %></li>
    <li><%= link_to "友達一覧", friends_path %></li>
    <li><%= link_to "タイムライン", timelines_path %></li>
    <li><%= link_to "友達を探す", users_path %></li>
  </ul>
</div>

app/views/home/about.html.erb
<div class="home">
  <h1>このサイトについて</h1>
  <p>工事中</p>
</div>

app/views/home/contact.html.erb
<div class="home">
  <h1>お問い合わせ</h1>
  <p>工事中</p>
</div>

app/views/home/friends.html.erb
<p class="friends_content">友達の数：<%= current_user.friends.count %></p>

<div class="friends_content">
  <p class=""><strong>全ての友達</strong></p>
  <% @friends.each do |friend| %>
    <div><%= friend.name %>  <%= link_to "トークへ", friend %></div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="home flex flex-direction justifyContent-center alignItems-center">
  <h1>"LINE"のようなアプリへようこそ！</h1>
  <%= link_to "ユーザー登録する", new_user_path %>
  <p>すでにアカウントがある方は<%= link_to "こちら", login_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LineApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="basicBlock">
      <div class="head flex alignItems-center justifyContent-center">
        <% if logged_in? %>
          <%= current_user.name %>
        <% end %>
      </div>
      <div class="flash">
        <% flash.each do |type, ms| %>
          <p class="flash_ms flash_ms-<%= type %>"><%= ms %></p>
        <% end %>
      </div>
      <div class="contents flex">
        <div class="contents_sidebar">
          <%= render "shared/sidebar" %>
        </div>

        <div class="contents_main">
          <%= yield %>
        </div>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/layouts/top_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LineApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="basicBlock">
      <div class="head flex alignItems-center justifyContent-center">
        <% if logged_in? %>
          <%= current_user.name %>
        <% end %>
      </div> 
      <div class="flash">
        <% flash.each do |type, ms| %>
          <p class="flash_ms flash_ms-<%= type %>"><%= ms %></p>
        <% end %>
      </div>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_error.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.full_messages.each do |ms| %>
    <ul>
      <li><%= ms %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="flex justifyContent-end">
  <ul class="flex">
    <% if logged_in? %>
      <li class="footer_list"><%= link_to "マイページ", current_user %></li>
    <% else %>
      <li class="footer_list"><%= link_to "トップへ", root_path %></li>
    <% end %>
    <li class="footer_list"><%= link_to "このサイトについて", about_path %></li>
    <li class="footer_list"><%= link_to "お問合せ", contact_path %></li>
    <% if logged_in? %>
      <li class="footer_list"><%= link_to "ログアウト", logout_path, method: :delete, data: { confirm: "ログアウトしますか？" } %></li>
    <% end %>
  </ul>
</footer>

app/views/shared/_sidebar.html.erb
<div class="flex flex-direction">
  <ul>
    <li><%= link_to "トーク一覧", "#"  %></li>
    <li><%= link_to "友達一覧", friends_path %></li>
    <li><%= link_to "タイムライン", timelines_path %></li>
    <li><%= link_to "友達を探す", users_path %></li>
  </ul>
</div>

app/views/timelines/index.html.erb
<div class="flex flex-direction justifyContent-center alignItems-center">
  <%= will_paginate @timelines %>
  <div>
    <% @timelines.each do |tl| %>
      <p class="txt-lrg"><%= tl.content %>  
      <% if current_user.id == tl.user_id %>
        <%= link_to "削除する", timeline_path(tl), class: "txt-med", method: :delete, data: { confirm: "削除しますか？" } %></p>
      <% end %>

      <p><%= tl.user.name %> <span class="txt-sml"><%= tl.created_at %></span></p>
    <% end %>
  </div>
  <%= will_paginate @timelines %>
  <div>
    <%= form_for(:tl, url: timelines_path) do |f| %>
      <%= f.text_field :content %>

      <%= f.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/users/_messages.html.erb
<div class="message" data-session="<%= session[:user_id] %>">
  <% user = User.find_by(id: @messages.from_user_id) %>
  <p class="<%= @messages.id %>" id="message_sender"><%= user.name %></p>
  <p class="<%= @messages.id %>" id="message_content"><%= @messages.content %></p>
</div>

app/views/users/_messages_form.html.erb
<form class="message_form">
  <input type="hidden" name="from_user_id" value="<%= from_user.id %>">
  <input type="hidden" name="to_user_id" value="<%= to_user.id %>">
  <input type="hidden" name="room_id" value="<%= room_id %>">
  <label>Send Message to <%= to_user.name %></label><br>
  <input type="text" name="content" data-behavior="chat_speaker">
</form>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
  <li>
    <% if !current_user?(user) %>
      <%= user.name %> 
      <% if  !current_user.from_friend?(user) && !user.to_friend?(current_user) %>
        <%= form_for(current_user.from_user_friendships.build) do |f| %>
          <%= hidden_field_tag :to_user_id, user.id %>
          <%= f.submit "友達になる" %>
        <% end %>
      <% end %>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="home flex flex-direction justifyContent-center alignItems-center">
  <%= form_for(@user) do |f| %>
		<%= render "shared/error" %>
    <p class="form_item"><%= f.label :name %>
    <%= f.text_field :name %></p>

    <p class="form_item"><%= f.label :email %>
        <%= f.email_field :email %></p>

    <p class="form_item"><%= f.label :password %>
      <%= f.password_field :password %></p>

    <p class="form_item"><%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %></p>

    <%= f.submit "登録" %>
  <% end %>
</div>

app/views/users/show.html.erb
<aside class="col-md-4">
  <% if !current_user?(@user) && logged_in? %>
    <section class="message_box">
      <div id="messages">
        <ul>
          <% @messages.each do |ms| %>
            <% if ms.from_user != @user %>
              <div class="messages_content messages_content-left">
                <li class="txt-lrg"><%= ms.content %></li>
                <li><%= ms.from_user.name %></li>
                <li><%= ms.created_at %></li>
              </div>
            <% else %>
              <div class="messages_content messages_content-right">
                <li class="txt-lrg"><%= ms.content %></li>
                <li><%= ms.from_user.name %></li>
                <li><%= ms.created_at %></li>
              </div>
            <% end %>
          <% end %>
        </ul>
      </div>
    </section>
    <div class="message_form">
      <%= form_for(message=Message.new, url: messages_path) do |f| %>
        <%= f.label :content %>
        <%= f.text_field :content %>

        <%= hidden_field_tag :to_user_id, @user.id %>
        <%= hidden_field_tag :room_id, @room_id %>
        
        <%= f.submit "送信" %>
      <% end %>
    </div>
  <% end %>
</aside>